### ISSUE TITLE
Output Error, missing corElev_avg

### ISSUE THREAD

**Issue by JRicardoPC** [geojames/pyBathySfM#4]
Hello, At first thanks for your software.

When I try to use your software, in the output csv the only data I get is h_a, the other columns are empty
![imagen](https://user-images.githubusercontent.com/14940593/145812358-5da7ca97-1327-4dc5-a81a-4c6b07e8c240.png)
Tried your sample data but got the same result.
![imagen](https://user-images.githubusercontent.com/14940593/145813190-23c7d4c5-2de6-48c6-ab4b-ee62f4ce5bf1.png)
What could be the problem?

**Comment by geojames** [comment]
Ricardo,
That usually happens when there is something off with the camera file. First, what photogrammetry software are you using? Second, can you provide a sample of the camera file you are inputting?

**Comment by JRicardoPC** [comment]
thanks for reply
At the end checking my input files, I have a problem with the the coordinate system was different from the one obtained with cloud compare, my mistake. About your sample, my mistake too -.-, I tried to use the point_cloud.csv file instead of  the samplePoints. with that, the software works perfect.
Sorry again, my mistake, 
Thanks for all
Ricardo
